# Generated by Django 3.2.7 on 2021-09-10 06:29

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('phone', models.IntegerField(unique=True, verbose_name='Phone number')),
                ('image', models.FileField(blank=True, null=True, upload_to='manager_image')),
                ('password_again', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Manager',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('phone', models.IntegerField(unique=True, verbose_name='Phone number')),
                ('image', models.FileField(blank=True, null=True, upload_to='staff_image')),
                ('password_again', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Staff',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
